REMOVED: windows releases (temporary).
This is because building for windows raises an error that prevent the release from being deployed.

Exit code: ENOENT. spawn prlctl ENOENT  stackTrace=
    Error: Exit code: ENOENT. spawn prlctl ENOENT
           at /Users/lorenzo/Developer/Node/colliderchat-prototype/node_modules/builder-util/src/util.ts:125:16
           at exithandler (child_process.js:302:5)
           at ChildProcess.errorhandler (child_process.js:314:5)
           at ChildProcess.emit (events.js:210:5)
           at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
           at onErrorNT (internal/child_process.js:456:16)
           at processTicksAndRejections (internal/process/task_queues.js:80:21)